### PR TITLE
upgrade to halogen 3

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
I've added Travis for this repository, which is going to be important if people are actually contributing. It only has a simple smoke test at the moment, but could you please rebase to check that it works?

**Comment by justinwoo** [comment]
Fairly sure caching output won't work in general though, especially with updated dependencies and all. It shaves maybe 15-30s from the build anyway afaict

**Comment by kwohlfahrt** [comment]
Yeah, that was optimistic.

**Comment by justinwoo** [comment]
There's a ticket on purescript/purescript about maybe checking content hashes, but it's not like builds take very long at all for libs. It would be nice if Travis instances weren't toasters though.

**Pull request merged**
